---

- name: write values template
  copy:
    content: |
      {{ manifest_file }}
    dest:  /tmp/manifest_{{ name }}-template.txt
  delegate_to: localhost

- name: compile values
  template:
    src: /tmp/manifest_{{ name }}-template.txt
    dest: /tmp/manifest_{{ name }}.yml

- name: kube create
  command: kubectl apply -n {{ namespace }} -f /tmp/manifest_{{ name }}.yml {{ inline_options }}

